version: "2"
linters:
  enable:
    - contextcheck
    - gosec
    - importas
    - intrange
    - misspell
    - tparallel
    - unparam
  settings:
    gosec:
      severity: low
      confidence: low
    importas:
      alias:
        - pkg: go.temporal.io/sdk/contrib/(\w+)
          alias: temporalsdk_contrib_$1
        - pkg: go.temporal.io/sdk/(\w+)
          alias: temporalsdk_$1
        - pkg: go.temporal.io/api/(\w+)
          alias: temporalapi_$1
      no-unaliased: true
      no-extra-aliases: false
  exclusions:
    generated: lax
    paths:
      - hack
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/artefactual-sdps/cva-enduro-workflows)
      no-inline-comments: true
      no-prefix-comments: false
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120
      chain-split-dots: true
      reformat-tags: true
      shorten-comments: true
  exclusions:
    generated: lax
    paths:
      - hack
run:
  timeout: 60s
