apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cva-enduro-secure
subjects:
  - kind: ServiceAccount
    name: cva-enduro
roleRef:
  kind: Role
  name: secure
  apiGroup: rbac.authorization.k8s.io
