// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// EventTypeCreation is a EventType of type Creation.
	EventTypeCreation EventType = "Creation"
	// EventTypeRecordkeeping is a EventType of type Recordkeeping.
	EventTypeRecordkeeping EventType = "Recordkeeping"
)

var ErrInvalidEventType = fmt.Errorf("not a valid EventType, try [%s]", strings.Join(_EventTypeNames, ", "))

var _EventTypeNames = []string{
	string(EventTypeCreation),
	string(EventTypeRecordkeeping),
}

// EventTypeNames returns a list of possible string values of EventType.
func EventTypeNames() []string {
	tmp := make([]string, len(_EventTypeNames))
	copy(tmp, _EventTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x EventType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x EventType) IsValid() bool {
	_, err := ParseEventType(string(x))
	return err == nil
}

var _EventTypeValue = map[string]EventType{
	"Creation":      EventTypeCreation,
	"Recordkeeping": EventTypeRecordkeeping,
}

// ParseEventType attempts to convert a string to a EventType.
func ParseEventType(name string) (EventType, error) {
	if x, ok := _EventTypeValue[name]; ok {
		return x, nil
	}
	return EventType(""), fmt.Errorf("%s is %w", name, ErrInvalidEventType)
}

func (x EventType) Ptr() *EventType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x EventType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *EventType) UnmarshalText(text []byte) error {
	tmp, err := ParseEventType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *EventType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errEventTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *EventType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = EventType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseEventType(v)
	case []byte:
		*x, err = ParseEventType(string(v))
	case EventType:
		*x = v
	case *EventType:
		if v == nil {
			return errEventTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errEventTypeNilPtr
		}
		*x, err = ParseEventType(*v)
	default:
		return errors.New("invalid type for EventType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x EventType) Value() (driver.Value, error) {
	return x.String(), nil
}

// Set implements the Golang flag.Value interface func.
func (x *EventType) Set(val string) error {
	v, err := ParseEventType(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *EventType) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *EventType) Type() string {
	return "EventType"
}

// Values implements the entgo.io/ent/schema/field EnumValues interface.
func (x EventType) Values() []string {
	return EventTypeNames()
}

// EventTypeInterfaces returns an interface list of possible values of EventType.
func EventTypeInterfaces() []interface{} {
	var tmp []interface{}
	for _, v := range _EventTypeNames {
		tmp = append(tmp, v)
	}
	return tmp
}

// ParseEventTypeWithDefault attempts to convert a string to a ContentType.
// It returns the default value if name is empty.
func ParseEventTypeWithDefault(name string) (EventType, error) {
	if name == "" {
		return _EventTypeValue[_EventTypeNames[0]], nil
	}
	if x, ok := _EventTypeValue[name]; ok {
		return x, nil
	}
	return EventType(""), fmt.Errorf("%s is not a valid EventType, try [%s]", name, strings.Join(_EventTypeNames, ", "))
}

// NormalizeEventType attempts to parse a and normalize string as content type.
// It returns the input untouched if name fails to be parsed.
// Example:
//
//	"enUM" will be normalized (if possible) to "Enum"
func NormalizeEventType(name string) string {
	res, err := ParseEventType(name)
	if err != nil {
		return name
	}
	return res.String()
}
