// Code generated by go-enum DO NOT EDIT.
// Version: 0.9.2
// Revision: 9d73c76728916582359433d1eb0b27340a8268b7
// Build Date: 2025-10-17T20:10:48Z
// Built By: goreleaser

package enums

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// TaskOutcomeUnspecified is a TaskOutcome of type unspecified.
	TaskOutcomeUnspecified TaskOutcome = "unspecified"
	// TaskOutcomeSuccess is a TaskOutcome of type success.
	TaskOutcomeSuccess TaskOutcome = "success"
	// TaskOutcomeSystemFailure is a TaskOutcome of type system failure.
	TaskOutcomeSystemFailure TaskOutcome = "system failure"
	// TaskOutcomeValidationFailure is a TaskOutcome of type validation failure.
	TaskOutcomeValidationFailure TaskOutcome = "validation failure"
)

var ErrInvalidTaskOutcome = fmt.Errorf("not a valid TaskOutcome, try [%s]", strings.Join(_TaskOutcomeNames, ", "))

var _TaskOutcomeNames = []string{
	string(TaskOutcomeUnspecified),
	string(TaskOutcomeSuccess),
	string(TaskOutcomeSystemFailure),
	string(TaskOutcomeValidationFailure),
}

// TaskOutcomeNames returns a list of possible string values of TaskOutcome.
func TaskOutcomeNames() []string {
	tmp := make([]string, len(_TaskOutcomeNames))
	copy(tmp, _TaskOutcomeNames)
	return tmp
}

// String implements the Stringer interface.
func (x TaskOutcome) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TaskOutcome) IsValid() bool {
	_, err := ParseTaskOutcome(string(x))
	return err == nil
}

var _TaskOutcomeValue = map[string]TaskOutcome{
	"unspecified":        TaskOutcomeUnspecified,
	"success":            TaskOutcomeSuccess,
	"system failure":     TaskOutcomeSystemFailure,
	"validation failure": TaskOutcomeValidationFailure,
}

// ParseTaskOutcome attempts to convert a string to a TaskOutcome.
func ParseTaskOutcome(name string) (TaskOutcome, error) {
	if x, ok := _TaskOutcomeValue[name]; ok {
		return x, nil
	}
	return TaskOutcome(""), fmt.Errorf("%s is %w", name, ErrInvalidTaskOutcome)
}

func (x TaskOutcome) Ptr() *TaskOutcome {
	return &x
}

// MarshalText implements the text marshaller method.
func (x TaskOutcome) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *TaskOutcome) UnmarshalText(text []byte) error {
	tmp, err := ParseTaskOutcome(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *TaskOutcome) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errTaskOutcomeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *TaskOutcome) Scan(value interface{}) (err error) {
	if value == nil {
		*x = TaskOutcome("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseTaskOutcome(v)
	case []byte:
		*x, err = ParseTaskOutcome(string(v))
	case TaskOutcome:
		*x = v
	case *TaskOutcome:
		if v == nil {
			return errTaskOutcomeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errTaskOutcomeNilPtr
		}
		*x, err = ParseTaskOutcome(*v)
	default:
		return errors.New("invalid type for TaskOutcome")
	}

	return
}

// Value implements the driver Valuer interface.
func (x TaskOutcome) Value() (driver.Value, error) {
	return x.String(), nil
}

// Set implements the Golang flag.Value interface func.
func (x *TaskOutcome) Set(val string) error {
	v, err := ParseTaskOutcome(val)
	*x = v
	return err
}

// Get implements the Golang flag.Getter interface func.
func (x *TaskOutcome) Get() interface{} {
	return *x
}

// Type implements the github.com/spf13/pFlag Value interface.
func (x *TaskOutcome) Type() string {
	return "TaskOutcome"
}

// Values implements the entgo.io/ent/schema/field EnumValues interface.
func (x TaskOutcome) Values() []string {
	return TaskOutcomeNames()
}

// TaskOutcomeInterfaces returns an interface list of possible values of TaskOutcome.
func TaskOutcomeInterfaces() []interface{} {
	var tmp []interface{}
	for _, v := range _TaskOutcomeNames {
		tmp = append(tmp, v)
	}
	return tmp
}

// ParseTaskOutcomeWithDefault attempts to convert a string to a ContentType.
// It returns the default value if name is empty.
func ParseTaskOutcomeWithDefault(name string) (TaskOutcome, error) {
	if name == "" {
		return _TaskOutcomeValue[_TaskOutcomeNames[0]], nil
	}
	if x, ok := _TaskOutcomeValue[name]; ok {
		return x, nil
	}
	return TaskOutcome(""), fmt.Errorf("%s is not a valid TaskOutcome, try [%s]", name, strings.Join(_TaskOutcomeNames, ", "))
}

// NormalizeTaskOutcome attempts to parse a and normalize string as content type.
// It returns the input untouched if name fails to be parsed.
// Example:
//
//	"enUM" will be normalized (if possible) to "Enum"
func NormalizeTaskOutcome(name string) string {
	res, err := ParseTaskOutcome(name)
	if err != nil {
		return name
	}
	return res.String()
}
